name: Build new Orly installer

on:
  # any tag assumed to mean "ready to release"
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    environment: production
    runs-on: windows-latest

    steps:
    - name: Fix PSGallery
      shell: pwsh
      run: |
        if (-not (Get-PSRepository -Name PSGallery -ErrorAction SilentlyContinue)) {
            Register-PSRepository -Default
        }
        Install-Module -Name Microsoft.WinGet.Client -Repository PSGallery -Force

    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Install the build tools and build the DLL
      run: ./Build.ps1

    - name: Download original Orly CD from archive.org
      run: $ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest https://archive.org/download/orly1996/ORLY.iso -OutFile ORLY.iso

    - name: Build a release
      run: ./Repack.ps1 -ISO ORLY.ISO

    - name: Zip the installed directory
      id: zip
      run: |
        $version = ((Get-ChildItem '.\tmp\*.exe').Name -split "[.-]")[-4..-2] -join "."
        tar -c -a -f "tmp\Orly's Draw-A-Story-$version.zip" -C tmp *Draw-A-Story
        "version=$version" >> $env:GITHUB_OUTPUT

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "${{ steps.zip.outputs.version }}"
        files: |
          tmp/*.exe
          tmp/*.zip
